<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-RKHPL37" ignored="0" name="Default test" tests="5" failures="1" timestamp="2020-09-17T00:43:57 IST" time="61.835" errors="0">
  <testcase name="TC01_verifyDragAndDrop" time="2.525" classname="testCases.Assignment1_DemoQA">
    <failure type="java.lang.IllegalArgumentException" message="imagePath cannot be null or empty">
      <![CDATA[java.lang.IllegalArgumentException: imagePath cannot be null or empty
at com.aventstack.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:1120)
at com.aventstack.extentreports.ExtentTest.addScreenCaptureFromPath(ExtentTest.java:1147)
at com.topgear.qa.pageObjects.DemoQADroppablePage.droppablePageVerify(DemoQADroppablePage.java:39)
at testCases.Assignment1_DemoQA.TC01_verifyDragAndDrop(Assignment1_DemoQA.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC01_verifyDragAndDrop -->
  <testcase name="TC02_verifyDatePicker" time="8.603" classname="testCases.Assignment1_DemoQA"/>
  <testcase name="TC03_verifySelectable" time="3.67" classname="testCases.Assignment1_DemoQA"/>
  <testcase name="TC04_verifySelectMenu" time="3.902" classname="testCases.Assignment1_DemoQA"/>
  <testcase name="TC05_verifyPracticeForm" time="6.06" classname="testCases.Assignment1_DemoQA"/>
</testsuite> <!-- Default test -->
